version: '3.8'
services:
  server:
    # image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - "8000:80"
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    # command: [nginx-debug, '-g', 'daemon off;'

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    #   - ./src:/var/www/html:delegated

  mysql:
    image: "mysql:5.7"
    env_file:
      - ./env/mysql.env

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ["php","/var/www/html/artisan"]

  npm:
    image: node
    working_dir: /var/www/html
    volumes:
      - ./src:var/www/html
    entrypoint: ['yarn']

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      links:
        - mysql
      environment:
        PMA_HOST: mysql

volumes:
  mysqldata:
    driver: "local"